run:
  timeout: 5m
  tests: true
  relative-path-mode: cfg
  issues-exit-code: 1

output:
  formats:
    - format: colored-line-number # Best for CLI usage
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - errcheck      # Checks for unchecked errors
    - govet         # Official Go tool
    - ineffassign   # Detects unused assignments
    - typecheck     # Parses and type-checks Go code
    - unused        # Checks for unused constants, variables, functions

    - staticcheck   # Massive set of best practice & style rules

    - revive        # Faster, configurable replacement for deprecated 'golint'
    - gosec         # Security scanner (SQL injection, hardcoded creds)
    - godoclint     # (New 2025) Validates comments against Go standards [web:101]

    - bodyclose     # Checks if HTTP response bodies are closed
    - noctx         # Ensures you send context.Context to functions that need it
    - dogsled       # Checks for too many blank identifiers (e.g. _, _, _, err)
    - unconvert     # Remove unnecessary type conversions
    - goconst       # Finds repeated strings that could be constants
    - exportloopref # Checks for pointers to enclosing loop variables

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments: ["disableStuttering"] # Check for types like "UserUser"
      - name: package-comments
        severity: warning
        disabled: false

  # gosec:
  #   excludes:
  #     - G101 # "Potential hardcoded credential" (often false positives in tests)
  #   config:
  #     G306: "0600" # Allow only strict file permissions
  #
  # staticcheck:
  #   checks: ["all", "-ST1000"] # Enable all, but disable package comment check

  # Goconst
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: tools/
      linters:
        - gochecknoglobals
