# golangci-lint configuration for dev-cli
# Focused on Docker API safety and common Go bugs
# Run: golangci-lint run ./...

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Critical for Docker SDK - catch unhandled errors
    - errcheck
    # Static analysis for common bugs
    - staticcheck
    # Lightweight linter, catches common mistakes
    - revive
    # Detect ineffectual assignments
    - ineffassign
    # Check for unchecked type assertions
    - unconvert
    # Detect unused code
    - unused
    # Check for goroutine leaks (important for streaming logs)
    - govet
    # Check printf-style functions
    - goprintffuncname

  disable:
    # Too noisy for dev tools
    - gocritic
    - gocyclo
    - funlen
    - gocognit

linters-settings:
  errcheck:
    # Check for ignored errors in defer statements
    check-blank: true
    # Don't report on explicitly ignored errors with _
    exclude-functions:
      - io.Copy
      - (io.Closer).Close

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: var-declaration
      - name: package-comments
        disabled: true # Not needed for internal packages

  staticcheck:
    checks:
      - all
      - -SA1019 # Ignore deprecation warnings for now

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  max-same-issues: 10

  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck

    # Exclude lll issues for long lines in go.mod
    - path: go\.mod
      linters:
        - lll
